### ISSUE TITLE
Newer PyApp releases are using a yanked version of zip, compilation fails

### ISSUE THREAD

**Issue by Tremeschin** [ofek/pyapp#135]
Hi, you'd probably notice this eventually but a lot of `zip` crate versions [were yanked](https://crates.io/crates/zip/versions) recently, including 1.2.3 currently specified on PyApp, so compilation fails for all recent versions newer than v0.19.0 from what I can tell

**Comment by ofek** [comment]
Good catch, thank you!

**Comment by ofek** [comment]
Fixed https://github.com/ofek/pyapp/releases/tag/v0.22.0
