### ISSUE TITLE
UV download not found

### ISSUE THREAD

**Issue by sandangel** [ofek/pyapp#139]
Hi, it seems like uv download for linux aarch64 could not be found when building pyapp.
from uv release, they only have `-musl` variant. can we fix the link to download for linux aarch64 or consider installing it from pypi or building from source if binary can not be downloaded?

**Comment by ofek** [comment]
Looks like a regression: https://github.com/astral-sh/uv/pull/3685

I'm investigating.

**Comment by henryiii** [comment]
The -musl variant works on -gnu, it's statically linked. Though maybe it should be duplicated with the -gnu suffix too?

**Comment by ofek** [comment]
The issue is that we use the build target to determine the proper UV artifact to download at runtime when that option is enabled.

I opened https://github.com/astral-sh/uv/issues/4122

**Comment by sandangel** [comment]
From the discussion on that issue, I guess we now should map gnu targets to musl then?

**Comment by ofek** [comment]
Fixed upstream, that release asset is back now.
