### ISSUE TITLE
Allow file system path for `PYAPP_DISTRIBUTION_SOURCE` when `PYAPP_DISTRIBUTION_EMBED=true`

### ISSUE THREAD

**Issue by layday** [ofek/pyapp#15]
To avoid having to fire up an HTTP server for the build when combining `source` with `skip_install` and `embed` (i.e. a custom dist in which the project has been pre-installed).  Essentially, this would allow `pyapp` to work the same way as pyinstaller single-file bundles, but with the distribution being persisted on disk.

**Comment by ofek** [comment]
What would you recommend as the ID when that happens? Currently, the ID is a hash of the source (with the assumption that the content is static)

**Comment by layday** [comment]
Can it be a hash of the archive?

**Comment by ofek** [comment]
After some sleep I realize that is clearly the obvious answer 😅 I will implement this sometime this week

Thanks!
