### ISSUE TITLE
[Quesion] Can I use this as an alertivative to pipx?

### ISSUE THREAD

**Issue by yozachar** [ofek/pyapp#151]
If yes, is it possible to publish pre-built binaries of `pyapp` on the GitHub release page?

**Comment by Coruscant11** [comment]
> If yes, is it possible to publish pre-built binaries of `pyapp` on the GitHub release page?

You can't, as pyapp is not used with a binary.
Executables are generated by compiling pyapp with environment variables

If what you want is standalone python for your pipx installations, maybe you can try to look at `uv` with the `uv tool` command ?
