### ISSUE TITLE
Reduce distribution size with install-only-stripped builds

### ISSUE THREAD

**Issue by Coruscant11** [ofek/pyapp#159]
Hello! 👋 

Since the [20240726 release of python-build-standalone](https://github.com/indygreg/python-build-standalone/releases/tag/20240726), a new kind of distributions builds are available.

> A new install_only_stripped variant is now included in the release (https://github.com/indygreg/python-build-standalone/pull/279). These builds are constructed by taking the install_only variant for each platform and stripping any debug symbols. The resulting builds are significantly smaller, especially on Windows and Linux, but omit debugging symbols. The install_only builds continue to preserve such symbols.

=> Smaller binaries with embeded distributions, and smaller downloads 🚀 

Some examples:
![image](https://github.com/user-attachments/assets/d4dbc63c-4912-430f-99ae-4f1312abfbbf)

![image](https://github.com/user-attachments/assets/f7dfded6-eac5-4837-ae91-e2786a34a371)

I will make a related pull-request 🙂

**Comment by T-256** [comment]
How about using uv as downstream python bootstrapper?

**Comment by Coruscant11** [comment]
> How about using uv as downstream python bootstrapper?

Indeed, I agree to the idea, but currently pyapp supports regular pip too..

**Comment by ofek** [comment]
https://github.com/ofek/pyapp/pull/160#issuecomment-2408805608
