### ISSUE TITLE
No module named 'utils'

### ISSUE THREAD

**Issue by earthyes** [ofek/pyapp#176]
Thanks for you creating so nice PyApp, but there is a question I met when I tried to run
My project content:
```
├── cv4/
│   ├── __init__.py
│   ├── main.py
│   ├── utils/
│   │   ├── a.py
```
If I only have main.py, it is successful to run and get an exe. However, if I add a package utils and add a.py, I import it in main.py, then I set environment variables,  
PYAPP_EXEC_SCRIPT、PYAPP_PROJECT_DEPENDENCY_FILE、PYAPP__PROJECT_DEPENDENCY_FILE_NAME、PYAPP_PROJECT_PATH、PYAPP_PROJECT_NAME、PYAPP_PROJECT_VERSION
the results:
```
C:\cv4>cv5.exe
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\pyapp\cache\scripts\2267595081175660887\main.py", line 7, in <module>
    from utils import a
ModuleNotFoundError: No module named 'utils'
```
Did I overlook setting other variables?
Or Can pyApp be suitable for  more complex project structures? For example, projects where different modules need to import files from different packages, such as when module a imports b, b imports c, and c imports `d?

**Comment by ofek** [comment]
Please write the environment variables and values that you're using.

**Comment by earthyes** [comment]
> Please write the environment variables and values that you're using.
Thank you for quickly answering me!
Afterwards I find  when I use the PYAPP_EXEC_MODULE to replace PYAPP_EXEC_SCRIPT, it is successful to build. Everything is ok. If anyone meets the same question, maybe my demo and script 'build_with_pyapp.ps1' can be useful https://github.com/earthyes/A-Computer-Vision-project-processed-by-PyApp/tree/master
