### ISSUE TITLE
Failure if /tmp and /home directories are on different devices

### ISSUE THREAD

**Issue by anjomro** [ofek/pyapp#37]
Hi, thanks for your work with PyApp, it seems like a great way to distribute an App without requiring the user to deal with Python & Pip Dependencies!

When I tried using it unfortunately it fails after downloading the python distribution with the following message:

>Error: unable to move /tmp/.tmpm0yLxY/394365705109672478 to /home/user/.cache/pyapp/distributions/394365705109672478
>
>Caused by:
>    Invalid cross-device link (os error 18)

I suspect that PyApp downloads the distribution to /tmp... Folder and tries to move it into the /home user folder. This however fails, since I have my /home directory encrypted, thus /tmp and /home are on different mountpoints.

I have created a PR that fixes this problem: https://github.com/ofek/pyapp/pull/36

**Comment by ofek** [comment]
https://github.com/ofek/pyapp/releases/tag/v0.10.0
