### ISSUE TITLE
Relative path

### ISSUE THREAD

**Issue by mortenee** [ofek/pyapp#40]
This looks potentially very useful for a project I'm working on where I essentially need to have my code as a totally portable directory which includes a python runtime in addition to my python code and lots of database drivers etc that can run in an offline environment. 

I basically do an install on my online computer and then move the resulting directory to potentially offline machines for the actual running of the code. 

I did a bit of testing but couldn't quite get it to work for me. I did as follows

export PYAPP_PROJECT_NAME=pwetl
export PYAPP_PROJECT_VERSION=0.1
export PYAPP_PYTHON_VERSION=3.10
export PYAPP_FULL_ISOLATION=1
export PYAPP_DISTRIBUTION_EMBED=1
export PYAPP_SKIP_INSTALL=1

cargo build --release
cargo install pyapp --force --root ~/bin/PWETL

Everyting seems to work with a pyapp executable created in ~/bin/PWETL/bin/ but I cant seem to figure out how to run a local python file with a relative path (needed since the directory will need to be moved around).

Is this possible, and which PYAPP_EXEC_MODULE / PYAPP_EXEC_SPEC / PYAPP_EXEC_CODE setting should I use for running ~/bin/PWETL/bin/main.py when the pyapp executable is in the same directory?
I tried I few ways but couldn't find one that worked...

**Comment by ofek** [comment]
Hello! Are there any dependencies? If so then you would need to make an archive of a distribution with your dependencies preinstalled to achieve an offline installation.

Though back to your question there are two ways:

1. I can add a new `PYAPP_EXEC_SCRIPT` option
2. You can turn your script into a package with an entry point, build the project, and finally embed it https://ofek.dev/pyapp/latest/config/#project-embedding

**Comment by mortenee** [comment]
There's quite av few dependencies including some non-python ones. That, plus the need to keep the code files easily editable, is why this looked like a potentially much better fit than something like pyinstaller.

For the same reason option 2 would not be a good fit. I often have to edit the code on the fly while in the offline (and otherwise restricted) environment. Option 1 would be perfect!

**Comment by ofek** [comment]
https://github.com/ofek/pyapp/releases/tag/v0.10.0
