### ISSUE TITLE
Running a custom distribution fails

### ISSUE THREAD

**Issue by apollo13** [ofek/pyapp#48]
After my last issue I tried to prepackage everything into a custom python distribution but I cannot seem to get it to work. As a test I want my binary to run `python -m http.server`:

```
curl -LO https://github.com/indygreg/python-build-standalone/releases/download/20230507/cpython-3.11.3%2B20230507-x86_64_v2-unknown-linux-gnu-install_only.tar.gz
PYAPP_SKIP_INSTALL=1 PYAPP_FULL_ISOLATION=1 PYAPP_DISTRIBUTION_FORMAT="tar|gzip" PYAPP_DISTRIBUTION_PATH=`pwd`/cpython-3.11.3%2B20230507-x86_64_v2-unknown-linux-gnu-install_only.tar.gz PYAPP_EXEC_MODULE=http.server PYAPP_PROJECT_NAME=test PYAPP_PROJECT_VERSION=1 cargo install pyapp --force --root /tmp/
```

This build fine and utilizes `PYAPP_DISTRIBUTION_PATH` to reuse the already downloaded distribution. Running the binary results in:
```
/tmp/bin/pyapp
Error: project execution failed, consider restoring from scratch

Caused by:
    No such file or directory (os error 2)
```
any hints?

**Comment by ofek** [comment]
For custom distributions you need to set all of these options usually https://ofek.dev/pyapp/latest/config/#custom

In this case the standalone builds that you're trying to use have a nested structure so you have to set `PYAPP_DISTRIBUTION_PYTHON_PATH` to `python/bin/python3` https://github.com/ofek/pyapp/blob/v0.10.1/build.rs#L535-L546

**Comment by apollo13** [comment]
You are absolutely right. Thank you for your help and sorry for the noise.

**Comment by ofek** [comment]
No worries, happy to help!
