### ISSUE TITLE
Prevent bootstrapping races

### ISSUE THREAD

**Issue by thejcannon** [ofek/pyapp#54]
:wave: 

As discussed in DM, it'd be great if I built a PyApp and tried running it in parallel if the bootstrapping didn't race.

**Comment by ofek** [comment]
Thanks! This will be the next feature.

**Comment by ofek** [comment]
I haven't forgotten this, it just takes a bit of care to handle in a cross-platform manner. I plan to use: https://docs.rs/fs4/latest/fs4/trait.FileExt.html
