### ISSUE TITLE
How to use pyapp with a poetry-based project

### ISSUE THREAD

**Issue by jrobbins-LiveData** [ofek/pyapp#60]
I'm not familiar with the Rust toolchain and have a Python Poetry-based project.  The requirements are captured in a `poetry.lock` file, although poetry can export `requirements.txt` if required.  How would I go about using this really interesting project to package my app for Windows desktop deployment?

**Comment by ofek** [comment]
https://ofek.dev/pyapp/latest/examples/#dependency-file-with-script

**Comment by Vuizur** [comment]
I published a small example application here: https://github.com/Vuizur/pyappexample (Look at build_with_pyapp.ps1).
