### ISSUE TITLE
How to re-install from scratch

### ISSUE THREAD

**Issue by oberluz** [ofek/pyapp#68]
HI,

I'm using MacOS and I created a custom project and installed it and run it fine at first. I then went to uninstall it by deleting $HOME/Library/Caches/pyapp and I tried to re-install it again but it complains:

Error: project execution failed, consider restoring from scratch
Caused by:
    No such file or directory (os error 2)

How do I restore from scratch?
Thanks

**Comment by oberluz** [comment]
Solved: delete ./Library/Application\ Support/pyapp

**Comment by ofek** [comment]
Did you try the restore command?

**Comment by oberluz** [comment]
Ah, thanks, will try that next time
