### ISSUE TITLE
Cannot use `PYAPP_DISTRIBUTION_PATH` (at least with locally embedded projects)

### ISSUE THREAD

**Issue by nmay231** [ofek/pyapp#79]
When embedding a local tar of a python distribution, I get the following error

```
  --- stderr
  thread 'main' panicked at build.rs:565:9:

  Unable to determine format for distribution source: 
```

(yes, `distribution_source` is an empty string, I checked).

This occurs when providing `PYAPP_PROJECT_PATH` (embedding a wheel), `PYAPP_DISTRIBUTION_PATH`, and `PYAPP_EXEC_SPEC`. Removing `PYAPP_DISTRIBUTION_PATH`, works but python is not bundled along with the binary.

I have an [example here](https://github.com/nmay231/pyapp_bug).

<details>

<summary>

full output of `make build-bugged`

</summary>

```
$ make build-bugged
poetry build -f wheel
Building pyapp-bug (0.1.0)
  - Building wheel
  - Built pyapp_bug-0.1.0-py3-none-any.whl
cd pyapp-latest && \
	PYAPP_PROJECT_PATH=../dist/pyapp_bug-0.1.0-py3-none-any.whl \
	PYAPP_DISTRIBUTION_PATH=./python-3.10.13.tar.gz \
	PYAPP_EXEC_SPEC=pyapp_bug.entry:main \
	cargo build --release
   Compiling pyapp v0.13.0 (/home/nmay/cur/pyapp_bug/pyapp-latest)
error: failed to run custom build command for `pyapp v0.13.0 (/home/nmay/cur/pyapp_bug/pyapp-latest)`

Caused by:
  process didn't exit successfully: `/home/nmay/cur/pyapp_bug/pyapp-latest/target/release/build/pyapp-fa2006654aeb24f9/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-env=PYAPP_PROJECT_DEPENDENCY_FILE=
  cargo:rustc-env=PYAPP__PROJECT_DEPENDENCY_FILE_NAME=
  cargo:rustc-env=PYAPP_PROJECT_NAME=pyapp-bug
  cargo:rustc-env=PYAPP_PROJECT_VERSION=0.1.0
  cargo:rustc-env=PYAPP__PROJECT_EMBED_FILE_NAME=pyapp_bug-0.1.0-py3-none-any.whl
  cargo:rustc-env=PYAPP_DISTRIBUTION_SOURCE=
  cargo:rustc-env=PYAPP__DISTRIBUTION_ID=12080488350626410958

  --- stderr
  thread 'main' panicked at build.rs:565:9:


  Unable to determine format for distribution source: 


  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:13: build-bugged] Error 101
```

</details>

**Comment by ofek** [comment]
https://ofek.dev/pyapp/latest/config/#distribution-embedding

`PYAPP_DISTRIBUTION_EMBED=true`

**Comment by ofek** [comment]
Also please note that the example repo you showed will not work because the official python.org distributions are not prebuilt, the distribution must be built with a Python binary existing somewhere within already.

**Comment by nmay231** [comment]
> the official python.org distributions are not prebuilt
I didn't realize the compressed file had to be precompiled, but of course that makes sense. Thanks!

I'll try to make a PR on the docs when I get back from work, but there is still an issue.

> You may set the PYAPP_DISTRIBUTION_EMBED option to true or 1 to embed the distribution in the executable at build time to avoid fetching it at runtime. You can set the PYAPP_DISTRIBUTION_PATH option to use a local path rather than fetching the source, which implicitly enables embedding.

It sounded like setting `PYAPP_DISTRIBUTION_PATH` should enable `PYAPP_DISTRIBUTION_EMBED`?

**Comment by ofek** [comment]
It should enable implicitly, is that not the case? Also can you confirm that enabling the embed option explicitly fixes your issue?

**Comment by nmay231** [comment]
Double checking, the option is actually enabled implicity (my bad), but didn't work due to another bug that I'll fix in the PR (build.rs:505 should be `local_path`).

Enabling embedding explicitly still doesn't work due to that bug.
