### ISSUE TITLE
Notebook execution mode

### ISSUE THREAD

**Issue by quinnhornblow** [ofek/pyapp#81]
I've created a fork that adds a PYAPP_EXEC_NOTEBOOK execution option. It works in the same way as PYAPP_EXEC_SCRIPT but a .ipynb file needs to be specified instead of a .py file. The `-m notebook [file.ipynb]` command is called at runtime.

Happy to submit a pull request if it's a feature you want to add.

Fork: https://github.com/quinnhornblow/pyapp
Example repo: https://github.com/quinnhornblow/pyapp_notebook

**Comment by ofek** [comment]
Yes please!

**Comment by ofek** [comment]
https://github.com/ofek/pyapp/pull/82

**Comment by ofek** [comment]
https://ofek.dev/pyapp/latest/config/#execution-mode
