### ISSUE TITLE
Incorrect exit code

### ISSUE THREAD

**Issue by TobyGiacometti** [ofek/pyapp#83]
While using the standalone Hatch binaries, I noticed that in some circumstances the exit code is incorrect. For more information, please check following issue: https://github.com/juftin/hatch-pip-compile/issues/66

**Comment by ofek** [comment]
Can you please provide exact steps for me to reproduce?

**Comment by TobyGiacometti** [comment]
```bash
cd /tmp
wget https://github.com/pypa/hatch/releases/download/hatch-v1.9.3/hatch-1.9.3-x86_64-unknown-linux-gnu.tar.gz
tar -xzf "$(basename "$_")"
sudo install hatch-1.9.3-x86_64-unknown-linux-gnu /usr/local/bin/hatch
mkdir /tmp/hatch-pip-compile-test
cd "$_"
cat <<'EOF' >hatch.toml
[env]
requires = [ "hatch-pip-compile" ]

[envs.default]
type = "pip-compile"
dependencies = [ "pyinfra>=2.9" ]
EOF
PIP_COMPILE_DISABLE=1 hatch -v env run --env default -- python --version
printf "%s\n" "$?"
```

When Hatch is installed through pip directly, the exit code of the `hatch run` command is correct (`1`), when using the standalone binary, it is incorrect (`0`).

**Comment by ofek** [comment]
https://github.com/pypa/hatch/pull/1389

**Comment by TobyGiacometti** [comment]
Thank you!
