### ISSUE TITLE
How to add `optional-dependencies`

### ISSUE THREAD

**Issue by trappitsch** [ofek/pyapp#84]
Great project, thanks for the wonderful work! I tried creating a `PyApp` package for a project that requires additional dependencies. With `pip`, the installation would simply be:

```
pip install my_package[extra]
```

However, I don't seem to be able to figure out how I can pass the `[extra]` to `PyApp` directly. Is it necessary in this case to create a `requirements.txt` file and pass that via `PYAPP_PROJECT_DEPENDENCY_FILE` or can the extra deps be passed directly?
Thanks!

**Comment by ofek** [comment]
Ah this was an oversight, I will add this feature as a new option. Thank you! I'm also open to contributions if you would like to make a PR 🙂

**Comment by trappitsch** [comment]
Sounds good, I will give this a try. Thanks for your fast answer! More coming soon - including hopefully a PR 🙂

**Comment by ofek** [comment]
https://github.com/ofek/pyapp/pull/85
