### ISSUE TITLE
can this lib work with streamlit?

### ISSUE THREAD

**Issue by sagregrevc** [ofek/pyapp#95]
can this lib work with local runnig streamlit with access to USB devices and outer .ini files?
https://streamlit.io/

**Comment by trappitsch** [comment]
I don't really see why not. However, generally you need to start your local streamlit programs with `streamlit run app.py`, which you can't directly do here. So you would basically have to write a python script, which runs your streamlit app within streamlit, e.g., using `subprocess.run`. However, it becomes a bit tedious. 

I guess one question is: Why streamlit then? I don't think it's really made for running it locally, you might be better off with a simple GUI if you want to deploy local...

**Comment by sagregrevc** [comment]
thank you

it much more simple for starting than other gui libs.
"simple gui" with different lib eat additional few week for education.
